# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections
local   all             all                                     trust

# IPv4 local
host    all             all             127.0.0.1/32            trust

# IPv6 local
host    all             all             ::1/128                 trust

# Docker internal network (semua service di doms-network)
host    all             all             0.0.0.0/0               scram-sha-256

# Replication connections
host    replication     repl_user       0.0.0.0/0               scram-sha-256