
# postgresql-node.conf - NODE 2/3/4 (BEM / HIMA / UKM)


listen_addresses = '*'
port = 5432
max_connections = 100

# ---- Logical Replication (sebagai SUBSCRIBER) ----
wal_level = logical
max_wal_senders = 10
max_replication_slots = 10
max_worker_processes = 10
max_logical_replication_workers = 4
max_sync_workers_per_subscription = 2

# ---- Logging ----
logging_collector = off
log_min_messages = warning
log_statement = 'none'

# ---- Memory ----
shared_buffers = 128MB
work_mem = 4MB
maintenance_work_mem = 64MB

# ---- Misc ----
timezone = 'Asia/Jakarta'
datestyle = 'iso, dmy'