
# postgresql-master.conf - NODE 1 (KEMAHASISWAAN)


listen_addresses = '*'
port = 5432
max_connections = 100

# ---- Logical Replication (sebagai PUBLISHER) ----
wal_level = logical
max_wal_senders = 10
max_replication_slots = 10
max_worker_processes = 10

# ---- FDW ----
shared_preload_libraries = ''

# ---- Logging ----
logging_collector = off
log_min_messages = warning
log_statement = 'none'

# ---- Memory ----
shared_buffers = 128MB
work_mem = 4MB
maintenance_work_mem = 64MB

# ---- Misc ----
timezone = 'Asia/Jakarta'
datestyle = 'iso, dmy'