
# redis.conf - DOMS


bind 0.0.0.0
port 6379
protected-mode yes
requirepass redis_pass123

#  Persistence 
save 900 1
save 300 10
save 60 10000
dir /data
dbfilename dump.rdb

#  Memory 
maxmemory 128mb
maxmemory-policy allkeys-lru

#  Logging 
loglevel notice

#  Key naming convention (dokumentasi, bukan config aktif) 
# session:<user_id>            -> cache sesi login (TTL sesuai expired_at)
# calendar:cache               -> cache daftar kalender kegiatan
# organization:active          -> cache daftar organisasi aktif